### PR TITLE
Add PHP 7 to test matrix

### PR DESCRIPTION
**Pull request by LukasReschke**

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Yes. Core doesn't really works. Especially the occ tool seem to not work.

**Comment by LukasReschke** [comment]
> Core doesn't really works.

Wrong. Works fine :speak_no_evil: 

>  Especially the occ tool seem to not work.

Erm? 

```
➜  master git:(list-apps-for-all-users) ✗ php -v
PHP 7.0.0beta1 (cli) (built: Jul 17 2015 21:47:49)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0-dev, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
➜  master git:(list-apps-for-all-users) ✗ ./occ status
ownCloud or one of the apps require upgrade - only a limited number of commands are available
  - installed: true
  - version: 8.2.0.2
  - versionstring: 8.2 pre alpha
  - edition:
```

**Comment by LukasReschke** [comment]
Likely one just needs to install the mysql PHP 7 module on Travis using pecl (or whatever9 from what I can tell :speak_no_evil:

**Comment by LukasReschke** [comment]
(as any other app operates on SQLite)

**Comment by gnarula** [comment]
Closing this since PHP 7 is already in the test matrix now

**Pull request closed without merging**
