### PR TITLE
Update getid3 library to a patched version

### LINKED ISSUE #518: Some embedded cover images are not shown
With the current development sources, Music app is able to show album cover images embedded in the MP3 files. This, however, does not work on all files. Especially, it never works if the image size is more than 16KB.

The root cause for this is the getID3 issue http://www.getid3.org/phpBB3/viewtopic.php?f=4&t=1930. A fix for this issue is now included in the main branch of getID3 (commit https://github.com/JamesHeinrich/getID3/commit/0e6c1a3bcef8219fede2c3ead13734296576bce5) but I'm not sure how the problem should be fixed for Music app.

Music app comes with its own version of getID3 but usually this version is not used. Instead, getID3 loaded by the core is used. On the other hand, getID3 has been already replaced with ID3Parser in the master branch of the core. ID3Parser is based on getID3 and has the same problem. I believe that core circumvents the problem by making a temporary copy of the music file before passing it to getID3 or ID3Parser.

### LINKED ISSUE #538: Never ending scan Process
Hi,

After updating to 0.3.12 and adding new music, i was asked to scan the audio files.
First i thought that there are to many files. But after deleting all files and adding 22 files the error is still there. Just saying Scanning music ... 0 of 22 forever. 

Error log
`Error  PHP PHP Startup: Unable to load dynamic library '/usr/lib/php/modules/openssl.so' - /usr/lib/php/modules/openssl.so: cannot open shared object file: No such file or directory at Unknown#0 2016-09-22T08:18:16+00:00
Error   PHP PHP Startup: Unable to load dynamic library '/usr/lib/php/modules/openssl.so' - /usr/lib/php/modules/openssl.so: cannot open shared object file: No such file or directory at Unknown#0 2016-09-22T08:18:12+00:00
Error   PHP Uncaught Error: Access to undeclared static property: OC\Files\Filesystem::$normalizedPathCache in /usr/share/webapps/owncloud/lib/private/Files/Filesystem.php:772 Stack trace: #0 /usr/share/webapps/owncloud/lib/private/Files/View.php(2032): OC\Files\Filesystem::normalizePath('/n01/files/Musi...') #1 /usr/share/webapps/owncloud/lib/private/Files/View.php(1150): OC\Files\View->unlockFile('/n01/files/Musi...', 1) #2 [internal function]: OC\Files\View->OC\Files\{closure}() #3 /usr/share/webapps/owncloud/3rdparty/icewind/streams/src/CallbackWrapper.php(109): call_user_func(Object(Closure)) #4 [internal function]: Icewind\Streams\CallbackWrapper->stream_close() #5 /usr/share/webapps/owncloud/lib/private/Files/Stream/OC.php(122): fclose(Resource id #637) #6 [internal function]: OC\Files\Stream\OC->stream_close() #7 {main} thrown at /usr/share/webapps/owncloud/lib/private/Files/Filesystem.php#772  2016-09-22T08:17:57+00:00
Error   PHP Uncaught Error: Access to undeclared static property: OC\Files\Filesystem::$normalizedPathCache in /usr/share/webapps/owncloud/lib/private/Files/Filesystem.php:772 Stack trace: #0 /usr/share/webapps/owncloud/lib/private/Files/View.php(2032): OC\Files\Filesystem::normalizePath('/n01/files/Musi...') #1 /usr/share/webapps/owncloud/lib/private/Files/View.php(1150): OC\Files\View->unlockFile('/n01/files/Musi...', 1) #2 [internal function]: OC\Files\View->OC\Files\{closure}() #3 /usr/share/webapps/owncloud/3rdparty/icewind/streams/src/CallbackWrapper.php(109): call_user_func(Object(Closure)) #4 [internal function]: Icewind\Streams\CallbackWrapper->stream_close() #5 /usr/share/webapps/owncloud/lib/private/Files/Stream/OC.php(122): fclose(Resource id #637) #6 [internal function]: OC\Files\Stream\OC->stream_close() #7 {main} thrown at /usr/share/webapps/owncloud/lib/private/Files/Filesystem.php#772  2016-09-22T08:17:57+00:00
Error   PHP Cannot 'break' 2 levels at /usr/share/webapps/owncloud/apps/music/3rdparty/getID3/getid3/module.audio.ogg.php#511   2016-09-22T08:17:48+00:00
Debug   music   update - mimetype audio/flac    2016-09-22T08:17:48+00:00
Debug   music   update - /n01/files/Music/Red - Of Beauty and Rage 2015 /01 Descent.flac    2016-09-22T08:17:48+00:00
Info    music   Rescan triggered    2016-09-22T08:17:48+00:00
Error   PHP PHP Startup: Unable to load dynamic library '/usr/lib/php/modules/openssl.so' - /usr/lib/php/modules/openssl.so: cannot open shared object file: No such file or directory at Unknown#0 2016-09-22T08:17:35+00:00
Error   PHP PHP Startup: Unable to load dynamic library '/usr/lib/php/modules/openssl.so' - /usr/lib/php/modules/openssl.so: cannot open shared object file: No such file or directory at Unknown#0 2016-09-22T08:17:28+00:00
Error   PHP Uncaught Error: Access to undeclared static property: OC\Files\Filesystem::$normalizedPathCache in /usr/share/webapps/owncloud/lib/private/Files/Filesystem.php:772 Stack trace: #0 /usr/share/webapps/owncloud/lib/private/Files/View.php(2032): OC\Files\Filesystem::normalizePath('/n01/files/Musi...') #1 /usr/share/webapps/owncloud/lib/private/Files/View.php(1150): OC\Files\View->unlockFile('/n01/files/Musi...', 1) #2 [internal function]: OC\Files\View->OC\Files\{closure}() #3 /usr/share/webapps/owncloud/3rdparty/icewind/streams/src/CallbackWrapper.php(109): call_user_func(Object(Closure)) #4 [internal function]: Icewind\Streams\CallbackWrapper->stream_close() #5 /usr/share/webapps/owncloud/lib/private/Files/Stream/OC.php(122): fclose(Resource id #637) #6 [internal function]: OC\Files\Stream\OC->stream_close() #7 {main} thrown at /usr/share/webapps/owncloud/lib/private/Files/Filesystem.php#772  2016-09-22T08:12:43+00:00
Error   PHP PHP Startup: Unable to load dynamic library '/usr/lib/php/modules/openssl.so' - /usr/lib/php/modules/openssl.so: cannot open shared object file: No such file or directory at Unknown#0 2016-09-22T08:12:42+00:00
Error   PHP PHP Startup: Unable to load dynamic library '/usr/lib/php/modules/openssl.so' - /usr/lib/php/modules/openssl.so: cannot open shared object file: No such file or directory at Unknown#0 2016-09-22T08:12:23+00:00`

### LINKED ISSUE #545: PHP Fatal Error when uploading some FLAC files
```
[error] 5030#5030: *9802 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot 'break' 2 levels in /srv/www/nextcloud/apps/music/3rdparty/getID3/getid3/module.audio.ogg.php on line 511" while reading response header from upstream, client: xx.xx.xx.xx, server: _, request: "PUT /nextcloud/remote.php/webdav/Music/Monty%20Alexander/Concrete%20Jungle%20-%20The%20Music%20of%20Bob%20Marley/10.%20Trench%20Town.flac-chunking-2622979690-3-2 HTTP/1.0", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "myhost.com"
2016/10/19 20:05:12 [error] 5030#5030: *9802 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Access to undeclared static property: OC\Files\Filesystem::$normalizedPathCache in /srv/www/nextcloud/lib/private/Files/Filesystem.php:773
Stack trace:
#0 /srv/www/nextcloud/lib/private/Files/View.php(2034): OC\Files\Filesystem::normalizePath('/laurent/files/...')
#1 /srv/www/nextcloud/lib/private/Files/View.php(1152): OC\Files\View->unlockFile('/laurent/files/...', 1)
#2 [internal function]: OC\Files\View->OC\Files\{closure}()
#3 /srv/www/nextcloud/apps/files_external/3rdparty/icewind/streams/src/CallbackWrapper.php(109): call_user_func(Object(Closure))
#4 [internal function]: Icewind\Streams\CallbackWrapper->stream_close()
#5 /srv/www/nextcloud/lib/private/Files/Stream/OC.php(123): fclose(Resource id #144)
#6 [internal function]: OC\Files\Stream\OC->stream_close()
#7 {main}
  thrown in /srv/www/nextcloud/lib/private/Files/Filesystem.php on line 773" while reading upstream, client: xx.xx.xx.xx, server: _, request: "PUT /nextcloud/remote.php/webdav/Music/Monty%20Alexander/Concrete%20Jungle%20-%20The%20Music%20of%20Bob%20Marley/10.%20Trench%20Town.flac-chunking-2622979690-3-2 HTTP/1.0", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "myhost.com"
```

### PR DESCRIPTION
**Pull request by paulijar**
Update the getid3 library to version 1.9.12 patched with commit https://github.com/JamesHeinrich/getID3/commit/0e6c1a3bcef8219fede2c3ead13734296576bce5.

This should be considered a temporary solution. The library should be updated to the official version 1.9.13 once that is available.

Fixes #518.
Fixes #538.
Fixes #545.

### CODE REVIEW

**Comment by gnarula** [comment]
LGTM. One thing to note is the `oc://` scheme is discontinued in both ownCloud (https://github.com/owncloud/core/issues/26381) and nextCloud(https://github.com/nextcloud/server/pull/1827).

AFAIK the only way out is to temporarily cache the file as is done by the MP3 Preview Provider (https://github.com/owncloud/core/blob/master/lib/private/Preview/MP3.php#L44) (@MorrisJobke do you think there's any other way?) in which case we can continue using the non patched version of getID3 as it works on the temporary copy (ref #518) 

IMHO the best long term solution would be to patch ID3Parser and add support for ID3V1 and APE v1 and v2 (if @LukasReschke is open to it). This would allow generating previews for all MP3 files and OGG Vorbis files using the interfaces (IPreview) provided by core.

**Comment by LukasReschke** [comment]
> IMHO the best long term solution would be to patch ID3Parser and add support for ID3V1 and APE v1 and v2 (if @LukasReschke is open to it). This would allow generating previews for all MP3 files and OGG Vorbis files using the interfaces (IPreview) provided by core.

Would welcome any commit for that at https://github.com/LukasReschke/ID3Parser :)

**Comment by paulijar** [comment]
Discontinuation of the oc:// scheme is bad news :(. Copying temporarily megabytes of data just to read a few kilobytes is very wasteful and would probably kill the performance of cover art loading in the Music app.

The preview generator of the core caches the preview pictures. Hence, the preview loading is slow only on the first time a file is listed. If we could use the core previews, we would also get the benefits of caching but, as said, it's a long term vision.

Maybe the API of ID3Parser could be extended so that there would be a second overload of `analyze`, accepting file pointer instead of the file name? Wouldn't that make the temporary copying unnecessary?

Even if updating the getid3 library wouldn't solve our problems in long term, I believe it is still a good idea in short term. If not for the cover images, then for #538/#545.

**Comment by gnarula** [comment]
> Maybe the API of ID3Parser could be extended so that there would be a second overload of analyze, accepting file pointer instead of the file name? Wouldn't that make the temporary copying unnecessary?

That seems like a good idea. I have to make sure it works well with external storages as well. I've worked a bit on this but it would require some changes upstream before it can be incorporated.

> Even if updating the getid3 library wouldn't solve our problems in long term, I believe it is still a good idea in short term. If not for the cover images, then for #538/#545.

Absolutely, merged! Thanks once again :)

**Pull request merged**
