### PR TITLE
ship old Nextcloud Mapper to support NC 26+

### PR DESCRIPTION
**Pull request by blizzz**
fixes https://github.com/owncloud/music/issues/1050

Ships `lib/public/AppFramework/Db/Mapper.php` from Nextcloud 25 with adjusted namespace.  Upon app init, an alias is created to `OCA\Music\Db\CompatibleMapper` which is used  later on, instead of directly referencing `\OCP\AppFramework\Db\Mapper`.

Tested successfully on both my dev setups of NC 25 and NC 26.

### CODE REVIEW

**Review by a3linux — APPROVED** [review]
Quickly verify on my test Nextcloud 26 installation. 
Works fine. 
Will test more.

**Comment by a3linux** [comment]
Tested such functions on Nextcloud 26.0
1. Basic music files import and management
2. Playlist created and play
3. App password generation
As the HTTPS self signed certificate issue for my local dev installation, DID NOT TEST client side.

**Comment by paulijar** [comment]
Great, thanks! I'll try to look into this within the next few days.

**Comment by blizzz** [comment]
Also upgraded my instance today and patched music with this. My key use case, subsonic via DSub, is working :)

**Comment by jjasoncool** [comment]
thank you, nice job.

**Comment by john-2000** [comment]
Nice job working

**Comment by shakeme** [comment]
Would be nice to see this merged.

**Comment by paulijar** [comment]
Seems to work fine on various versions of ownCloud, too. I made a few cosmetic changes to make it ready for merging.

**Comment by blizzz** [comment]
Thank you @paulijar!

**Comment by paulijar** [comment]
@Ana-Khouri No promises, but I hope that I get the release done this week.

**Comment by paulijar** [comment]
The release v1.8.2 with this support for NC26 is now out!

**Comment by AubinF** [comment]
🔥 Thanks ! @paulijar

**Pull request merged**
