### PR TITLE
Fixed the "Blank page with asset-pipeline.enabled" bug #434

### PR DESCRIPTION
**Pull request by paulijar**
- Minification broke the injection because annotation was missing

### CODE REVIEW

**Comment by Gomez** [comment]
Works! :+1: 
@gnarula Is this good to merge? 

@paulijar Congrats! Great work!

**Comment by gnarula** [comment]
Album arts break for me when I enable asset-pipelining :( @Gomez @paulijar do you guys get a traceback like this in the console https://paste.gnome.org/pgsjmbcln ?

**Comment by gnarula** [comment]
I think I got it. There's an annotation missing in the albumart directive (`$http`). @paulijar could you please update `js/public/app.js` and `js/app/directives/albumart.js` and update the PR?

Thanks for your PR once again :)

**Comment by paulijar** [comment]
I figured out the same just before reading your latest comment :). For some reason, the albumart problem was not present when I was originally testing this on top of the release version (0.3.11) of the music app. But with the latest sources from github the problem was there.

**Pull request merged**
