### PR TITLE
[WIP] New playlist functionality (Final)

### PR DESCRIPTION
**Pull request by vgezer**
:construction: Work in progress!

Ready:
- [x] Sidebar with playlists
- [x] Hardcoded playlists
- [x] Hardcoded song display
- [x] Playlist - Database connection
- [x] Create basic playlist functionalities (create, edit, delete playlist)
- [x] Play the next song in the playlist after the current song
- [x] Add songs by drag&drop
- [x] Remove songs from playlists

Playlists:
- [x] Repeat playlist songs
- [x] Shuffle playlist songs

Working on:
- [ ] Design improvements

To do:
- [ ] Unit tests
- [ ] Documentation

Issues:

Apps menu is not shown: change z-index
Shuffle & repeat buttons are not shown, check css
Mobile view

Playlists may:
- [ ] be sorted by dragging

... and will be updated

### CODE REVIEW

**Comment by jancborchardt** [comment]
@MorrisJobke @vgezer so what’s the status on this?

**Comment by remiheens** [comment]
So, Do you have an idea about the release date ?

**Comment by jancborchardt** [comment]
@vgezer can you give any indication what you are up to? ;) Or @MorrisJobke what do you think is the state of this?

(@remiheens no idea basically – are you up to contribute maybe? :)

**Comment by vgezer** [comment]
I think I will be contributing to ownCloud in general as well as this repo from July again :). I haven't tested this for OC9, but @remiheens can give it a try and let us know :)

**Comment by remiheens** [comment]
Yes, I will test your branch on OC9.

**Comment by remiheens** [comment]
Ok, I've tested this PR. 

Playing music still works, Create playlist in sidebar works but
- Playlist icons on hover don't exist.
- Playlist view don't work (api/playlists/2/add return a 200 - {"name":"TEST","trackIds":[1],"id":2} )

See my log : 
```
[
    {
        "app": "PHP",
        "level": 3,
        "message": "Declaration of OCA\\Music\\Db\\PlaylistMapper::delete() should be compatible with OCP\\AppFramework\\Db\\Mapper::delete(OCP\\AppFramework\\Db\\Entity $entity) at /var/www/owncloud/apps/music/db/playlistmapper.php#20",
        "method": "GET",
        "remoteAddr": "89.91.146.13",
        "reqId": "6uDrQPIzG/60kkkODNZ9",
        "time": "2016-05-02T15:46:31+00:00",
        "url": "/index.php/apps/music/api/playlists/2",
        "user": "Remi"
    },
    {
        "app": "PHP",
        "level": 3,
        "message": "Missing argument 2 for OCA\\Music\\Db\\Track::toCollection(), called in /var/www/owncloud/apps/music/controller/playlistapicontroller.php on line 126 and defined at /var/www/owncloud/apps/music/db/track.php#94",
        "method": "GET",
        "remoteAddr": "89.91.146.13",
        "reqId": "6uDrQPIzG/60kkkODNZ9",
        "time": "2016-05-02T15:46:31+00:00",
        "url": "/index.php/apps/music/api/playlists/2",
        "user": "Remi"
    },
    {
        "app": "PHP",
        "level": 3,
        "message": "Undefined variable: userFolder at /var/www/owncloud/apps/music/db/track.php#95",
        "method": "GET",
        "remoteAddr": "89.91.146.13",
        "reqId": "6uDrQPIzG/60kkkODNZ9",
        "time": "2016-05-02T15:46:31+00:00",
        "url": "/index.php/apps/music/api/playlists/2",
        "user": "Remi"
    },
    {
        "app": "PHP",
        "level": 3,
        "message": "Call to a member function getById() on null at /var/www/owncloud/apps/music/db/track.php#95",
        "method": "GET",
        "remoteAddr": "89.91.146.13",
        "reqId": "6uDrQPIzG/60kkkODNZ9",
        "time": "2016-05-02T15:46:31+00:00",
        "url": "/index.php/apps/music/api/playlists/2",
        "user": "Remi"
    },
    {
        "app": "PHP",
        "level": 3,
        "message": "Declaration of OCA\\Music\\Db\\PlaylistMapper::delete() should be compatible with OCP\\AppFramework\\Db\\Mapper::delete(OCP\\AppFramework\\Db\\Entity $entity) at /var/www/owncloud/apps/music/db/playlistmapper.php#20",
        "method": "GET",
        "remoteAddr": "89.91.146.13",
        "reqId": "4CNoEX5lPKKRJc5bvaiJ",
        "time": "2016-05-02T15:46:31+00:00",
        "url": "/index.php/apps/music/api/playlists",
        "user": "Remi"
    }
]
```

To install this branch, i've checkout on master then merge branch playlist-last on it and composer/bower update.

If I've time, I will debugging OC9 compatibility.

**Comment by vgezer** [comment]
Thanks for working on it!

**Comment by remiheens** [comment]
Ok, I fixed the functionality for OC9. Everything works well.
How do you want me to send you the changes?

**Comment by jancborchardt** [comment]
I guess best would be a pull request which supersedes this one? Because that will have both @vgezer’s and your changes. :)

**Comment by remiheens** [comment]
A pull request on this branch ? (playlist-last) 

Sorry, but this is my first public contribution.
I have to fork owncloud/music repository, checkout on playlist-last, apply changes, push my forked playlist-last, and crate a PR for my own playlist-last branch ?

**Comment by jancborchardt** [comment]
Yep, exactly. And create the PR against the master branch. Then the changes by @vgezer and @MorrisJobke will automatically be in the PR since you based it off playlist-last. :)

Also, welcome to ownCloud! :)

**Comment by paulijar** [comment]
Superseded by #555

**Pull request closed without merging**
