### PR TITLE
Fix phpunit call to generate clover file

### PR DESCRIPTION
**Pull request by DeepDiver1975**
@MorrisJobke

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
coverage is now generated and uploaded to scrutinizer - https://travis-ci.org/owncloud/music/jobs/61294230#L147

**Comment by MorrisJobke** [comment]
https://scrutinizer-ci.com/g/owncloud/music/?branch=master <- code coverage: not enabled

**Comment by DeepDiver1975** [comment]
because master was not yet inspected successful since is was enabled - https://github.com/owncloud/music/blob/master/.scrutinizer.yml#L9

**Comment by MorrisJobke** [comment]
Thx

**Pull request merged**
