### PR TITLE
Update

### PR DESCRIPTION
**Pull request by Justman10000**

### CODE REVIEW

**Comment by Justman10000** [comment]
Well, having the latest of everything can never hurt

**Comment by Justman10000** [comment]
Sure, you have to adapt the source code... Reasons for this are these permament warnings of outdated and/or abandoned major versions or even whole modules

**Comment by Justman10000** [comment]
Sure, one has to adapt the source code... Reasons for this are these permament warnings of outdated and/or abandoned major versions or even whole modules

**Comment by paulijar** [comment]
> Well, having the latest of everything can never hurt

Sure it can, and this PR just clearly demonstrated that.

> Sure, one has to adapt the source code... 

So feel free to submit a PR where you include also those mandatory source code changes. Any half-assed attempt to update the dependencies, breaking everything along the way, does not benefit anyone.

> Reasons for this are these permament warnings of outdated and/or abandoned major versions or even whole modules

So did the updates proposed here remove any of those warnings? I *think* that most of the warnings are related either directly or indirectly to AngularJS, which as stated elsewhere, would be a huge struggle to replace.

**Comment by Justman10000** [comment]
To be able to test something in general, I would need to be able to use the plugin via the source code

**Comment by paulijar** [comment]
Obviously, and it will be rather pointless to create any PRs before you have the ability to test them. Have you tested what I suggested in https://github.com/owncloud/music/issues/1080#issuecomment-1677855789? Also, when you have the signature problem, can you find any additional clues from owncloud.log or nextcloud.log?

**Pull request closed without merging**
