### PR TITLE
Action not supported message

### PR DESCRIPTION
**Pull request by AshotN**
I think giving a more understandable error message will be more helpful to developers.

### CODE REVIEW

**Comment by morsik** [comment]
Shouldn't be `405`? https://github.com/ampache/ampache/wiki/XML-API-ERRORS

**Comment by AshotN** [comment]
I wasn't looking at the Ampache error codes, I was referencing HTTP error codes https://en.wikipedia.org/wiki/List_of_HTTP_status_codes.

**Comment by morsik** [comment]
@AshotN: see this: https://github.com/owncloud/music/blob/0c0e1fadbe31a43f9c98d6a2a7b3960ff881ca0e/middleware/ampachemiddleware.php#L101

Second parameter in `AmpacheException` is not HTTP status code, but Ampache status code.

**Comment by AshotN** [comment]
Changed it, but I have to say it seems odd to return what seems like an HTTP code as an Ampache code.

**Comment by paulijar** [comment]
@gnarula This change seems justifiable to me. Is there any reason why this hasn't been merged for 6 months?

**Comment by gnarula** [comment]
Nope, looks good to be merged

**Pull request merged**
